export default {
    food: {
        good: '((おい|美味)し|(まず|マズ|不味)く(な|にゃ)|うま|旨)い',
        bad: '(まず|マズ|不味|(おい|美味)しく(な|にゃ)|(うま|旨)く(な|にゃ))い',
        foods: [
            { emoji: '🍇', keywords: ['🍇', 'grapes', 'ぶどう', 'ブドウ', '葡萄'] },
            { emoji: '🍈', keywords: ['🍈', 'melon', 'メロン', '舐瓜'] },
            { emoji: '🍉', keywords: ['🍉', 'watermelon', 'スイカ', '西瓜'] },
            { emoji: '🍊', keywords: ['🍊', 'tangerine', 'オレンジ', 'みかん', '蜜柑'] },
            { emoji: '🍋', keywords: ['🍋', 'lemon', 'レモン', '檸檬'] },
            { emoji: '🍌', keywords: ['🍌', 'banana', 'バナナ'] },
            { emoji: '🍍', keywords: ['🍍', 'pineapple', 'パイナップル'] },
            { emoji: '🥭', keywords: ['🥭', 'mango', 'マンゴー'] },
            { emoji: '🍎', keywords: ['🍎', 'red apple', 'りんご', 'リンゴ', '林檎'] },
            { emoji: '🍏', keywords: ['🍏', 'green apple', '青りんご', '青リンゴ', '青林檎'] },
            { emoji: '🍐', keywords: ['🍐', 'pear', 'ナシ', '梨'] },
            { emoji: '🍑', keywords: ['🍑', 'peach', 'モモ', '桃'] },
            { emoji: '🍒', keywords: ['🍒', 'cherries', 'さくらんぼ', '桜桃'] },
            { emoji: '🍓', keywords: ['🍓', 'strawberry', 'いちご', '苺'] },
            { emoji: '🫐', keywords: ['🫐', 'blueberries', 'ブルーベリー'] },
            { emoji: '🥝', keywords: ['🥝', 'kiwi fruit', 'キウイ'] },
            { emoji: '🍅', keywords: ['🍅', 'tomato', 'トマト'] },
            { emoji: '🫒', keywords: ['🫒', 'olive', 'オリーブ'] },
            { emoji: '🥥', keywords: ['🥥', 'coconut', 'ココナッツ'] },
            { emoji: '🥑', keywords: ['🥑', 'avocado', 'アボカド'] },
            { emoji: '🍆', keywords: ['🍆', 'eggplant', 'ナス', '茄子'] },
            { emoji: '🥔', keywords: ['🥔', 'potato', 'ポテト', 'じゃがいも'] },
            { emoji: '🥕', keywords: ['🥕', 'carrot', 'にんじん', '人参'] },
            { emoji: '🌽', keywords: ['🌽', 'ear of corn', 'とうもろこし', 'コーン'] },
            { emoji: '🌶', keywords: ['🌶', 'hot pepper', 'とうがらし', '唐辛子'] },
            { emoji: '🫑', keywords: ['🫑', 'bell pepper', 'ピーマン'] },
            { emoji: '🥒', keywords: ['🥒', 'cucumber', 'きゅうり'] },
            { emoji: '🥬', keywords: ['🥬', 'leafy green', '野菜'] },
            { emoji: '🥦', keywords: ['🥦', 'broccoli', 'ブロッコリー'] },
            { emoji: '🧄', keywords: ['🧄', 'garlic', 'ガーリック', 'にんにく'] },
            { emoji: '🧅', keywords: ['🧅', 'onion', 'オニオン', 'たまねぎ', '玉ねぎ'] },
            { emoji: '🍄', keywords: ['🍄', 'mushroom', 'きのこ', 'マッシュルーム'] },
            { emoji: '🥜', keywords: ['🥜', 'peanuts', 'ピーナッツ'] },
            { emoji: '🌰', keywords: ['🌰', 'chestnut', '栗', 'くり'] },
            { emoji: '🍞', keywords: ['🍞', 'bread', 'パン'] },
            { emoji: '🥐', keywords: ['🥐', 'croissant', 'クロワッサン'] },
            { emoji: '🥖', keywords: ['🥖', 'baguette bread', 'バゲット', 'フランスパン'] },
            { emoji: '🫓', keywords: ['🫓', 'flatbread', 'フラットブレッド'] },
            { emoji: '🥨', keywords: ['🥨', 'pretzel', 'プレッツェル'] },
            { emoji: '🥯', keywords: ['🥯', 'bagel', 'ベーグル'] },
            { emoji: '🥞', keywords: ['🥞', 'pancakes', 'パンケーキ', 'ホットケーキ'] },
            { emoji: '🧇', keywords: ['🧇', 'waffle', 'ワッフル'] },
            { emoji: '🧀', keywords: ['🧀', 'cheese wedge', 'チーズ'] },
            { emoji: '🍖', keywords: ['🍖', 'meat on bone', '骨付き肉'] },
            { emoji: '🍗', keywords: ['🍗', 'poultry leg', '骨付きチキン'] },
            { emoji: '🥩', keywords: ['🥩', 'cut of meat', '肉'] },
            { emoji: '🥓', keywords: ['🥓', 'bacon', 'ベーコン'] },
            { emoji: '🍔', keywords: ['🍔', 'hamburger', 'ハンバーガー'] },
            { emoji: '🍟', keywords: ['🍟', 'french fries', 'フライドポテト', 'フレンチフライ'] },
            { emoji: '🍕', keywords: ['🍕', 'pizza', 'ピザ'] },
            { emoji: '🌭', keywords: ['🌭', 'hot dog', 'ホットドッグ'] },
            { emoji: '🥪', keywords: ['🥪', 'sandwich', 'サンドイッチ'] },
            { emoji: '🌮', keywords: ['🌮', 'taco', 'タコス'] },
            { emoji: '🌯', keywords: ['🌯', 'burrito', 'ブリート'] },
            { emoji: '🫔', keywords: ['🫔', 'tamale', 'タマル'] },
            { emoji: '🥙', keywords: ['🥙', 'stuffed flatbread', 'ギロピタ'] },
            { emoji: '🧆', keywords: ['🧆', 'falafel', 'ファラフェル'] },
            { emoji: '🥚', keywords: ['🥚', 'egg', '卵', '玉子', 'たまご'] },
            { emoji: '🍳', keywords: ['🍳', 'cooking', '料理'] },
            { emoji: '🥘', keywords: ['🥘', 'shallow pan of food', '浅い鍋'] },
            { emoji: '🍲', keywords: ['🍲', 'pot of food', '鍋'] },
            { emoji: '🫕', keywords: ['🫕', 'fondue', 'フォンデュ'] },
            { emoji: '🥣', keywords: ['🥣', 'bowl with spoon', 'ボウルとスプーン'] },
            { emoji: '🥗', keywords: ['🥗', 'green salad', 'サラダ'] },
            { emoji: '🍿', keywords: ['🍿', 'popcorn', 'ポップコーン'] },
            { emoji: '🧈', keywords: ['🧈', 'butter', 'バター'] },
            { emoji: '🧂', keywords: ['🧂', 'salt', '塩'] },
            { emoji: '🥫', keywords: ['🥫', 'canned food', '缶詰'] },
            { emoji: '🍱', keywords: ['🍱', 'bento box', '弁当'] },
            { emoji: '🍘', keywords: ['🍘', 'rice cracker', 'せんべい'] },
            { emoji: '🍙', keywords: ['🍙', 'rice ball', 'おにぎり'] },
            { emoji: '🍚', keywords: ['🍚', 'cooked rice', 'ご飯', 'ごはん'] },
            { emoji: '🍛', keywords: ['🍛', 'curry rice', 'カレー'] },
            { emoji: '🍜', keywords: ['🍜', 'steaming bowl', 'どんぶり', 'ラーメン'] },
            { emoji: '🍝', keywords: ['🍝', 'spaghetti', 'スパゲッティ'] },
            { emoji: '🍠', keywords: ['🍠', 'roasted sweet potato', 'スイートポテト'] },
            { emoji: '🍢', keywords: ['🍢', 'oden', 'おでん'] },
            { emoji: '🍣', keywords: ['🍣', 'sushi', 'すし', '寿司', '鮨'] },
            { emoji: '🍤', keywords: ['🍤', 'fried shrimp', '天ぷら'] },
            { emoji: '🍥', keywords: ['🍥', 'fish cake with swirl', 'なると'] },
            { emoji: '🥮', keywords: ['🥮', 'moon cake', '月餅'] },
            { emoji: '🍡', keywords: ['🍡', 'dango', '団子'] },
            { emoji: '🥟', keywords: ['🥟', 'dumpling', '餃子'] },
            { emoji: '🥠', keywords: ['🥠', 'fortune cookie', 'フォーチュンクッキー'] },
            { emoji: '🥡', keywords: ['🥡', 'takeout box', 'テイクアウトボックス'] },
            { emoji: '🦀', keywords: ['🦀', 'crab', 'カニ', '蟹'] },
            { emoji: '🦞', keywords: ['🦞', 'lobster', 'ロブスター'] },
            { emoji: '🦐', keywords: ['🦐', 'shrimp', 'エビ', '海老'] },
            { emoji: '🦑', keywords: ['🦑', 'squid', 'イカ', '烏賊'] },
            { emoji: '🐙', keywords: ['🐙', 'octopus', 'タコ', '蛸'] },
            { emoji: '🦪', keywords: ['🦪', 'oyster', 'カキ', '牡蠣'] },
            { emoji: '🍦', keywords: ['🍦', 'soft ice cream', 'ソフトクリーム'] },
            { emoji: '🍧', keywords: ['🍧', 'shaved ice', 'シャーベット'] },
            { emoji: '🍨', keywords: ['🍨', 'ice cream', 'アイスクリーム', 'アイス'] },
            { emoji: '🍩', keywords: ['🍩', 'doughnut', 'ドーナツ', 'ドーナッツ'] },
            { emoji: '🍪', keywords: ['🍪', 'cookie', 'クッキー'] },
            { emoji: '🎂', keywords: ['🎂', 'birthday cake', '誕生日ケーキ'] },
            { emoji: '🍰', keywords: ['🍰', 'shortcake', 'ショートケーキ', 'ケーキ'] },
            { emoji: '🧁', keywords: ['🧁', 'cupcake', 'カップケーキ'] },
            { emoji: '🥧', keywords: ['🥧', 'pie', 'パイ'] },
            { emoji: '🍫', keywords: ['🍫', 'chocolate bar', 'チョコ'] },
            { emoji: '🍬', keywords: ['🍬', 'candy', 'キャンディー', 'あめ'] },
            { emoji: '🍭', keywords: ['🍭', 'lollipop', 'ロリポップ', 'あめ', 'ペロペロキャンディー'] },
            { emoji: '🍮', keywords: ['🍮', 'custard', 'プリン'] },
            { emoji: '🍯', keywords: ['🍯', 'honey pot', 'はちみつ', 'ハニー'] },
            { emoji: '🍼', keywords: ['🍼', 'baby bottle', '哺乳瓶'] },
            { emoji: '🥛', keywords: ['🥛', 'glass of milk', '牛乳', 'ミルク'] },
            { emoji: '☕', keywords: ['☕', 'hot beverage', 'コーヒー'] },
            { emoji: '🫖', keywords: ['🫖', 'teapot', 'ティーポット'] },
            { emoji: '🍵', keywords: ['🍵', 'teacup without handle', 'お茶'] },
            { emoji: '🍶', keywords: ['🍶', 'sake', '酒'] },
            { emoji: '🍾', keywords: ['🍾', 'bottle with popping cork', 'コルクボトル'] },
            { emoji: '🍷', keywords: ['🍷', 'wine glass', 'ワイン'] },
            { emoji: '🍸', keywords: ['🍸', 'cocktail glass', 'カクテル'] },
            { emoji: '🍹', keywords: ['🍹', 'tropical drink', 'トロピカルドリンク'] },
            { emoji: '🍺', keywords: ['🍺', 'beer mug', 'ビール'] },
            { emoji: '🍻', keywords: ['🍻', 'clinking beer mugs', '乾杯'] },
            { emoji: '🥂', keywords: ['🥂', 'clinking glasses', '乾杯'] },
            { emoji: '🥃', keywords: ['🥃', 'tumbler glass', 'タンブラー', 'ウイスキー'] },
            { emoji: '🥤', keywords: ['🥤', 'cup with straw', 'ストロー'] },
            { emoji: '🧋', keywords: ['🧋', 'bubble tea', 'タピオカ'] },
            { emoji: '🧃', keywords: ['🧃', 'beverage box', 'パック飲料'] },
            { emoji: '🧉', keywords: ['🧉', 'mate', 'マテ茶'] },
            { emoji: '🧊', keywords: ['🧊', 'ice', '氷', 'アイス'] },
            { emoji: '🥢', keywords: ['🥢', 'chopsticks', '箸'] },
            { emoji: '🍽', keywords: ['🍽', 'fork and knife with plate', 'プレート'] },
            { emoji: '🍴', keywords: ['🍴', 'fork and knife', 'ナイフとフォーク'] },
            { emoji: '🥄', keywords: ['🥄', 'spoon', 'スプーン'] },
            { emoji: '🔪', keywords: ['🔪', 'kitchen knife', '包丁'] },
            { emoji: '🏺', keywords: ['🏺', 'amphora', 'アンフォラ'] },
            // ばすきーオリジナル仕様
            { emoji: ':daiconsexy:', keywords: ['大根', 'だいこん']},
            { emoji: ':daiconwalk:', keywords: ['大根', 'だいこん']},

            // ぶろきゃ
            { emoji: ':pann:', keywords: ['パン']},
            { emoji: ':ameowcoffee:', keywords: ['コーヒー', '珈琲', '紅茶', 'ヌン茶', '茶しばき', '茶']},
            { emoji: ':ameowshipzoom:', keywords: ['ジュース']},
            { emoji: ':blobcatbreadpeek:', keywords: ['パン']},
            { emoji: ':blobcat_chikuwa:', keywords: ['ちくわ', '竹輪']},
            { emoji: ':blobcat_inhale_the_cupmeowdle:', keywords: ['カップ麺', 'カプ麺', 'カップヌードル']},
            { emoji: ':blobcatnomblobbunny:', keywords: ['うさぎ', '兎']},
            { emoji: ':blobcat_nomcookie:', keywords: ['クッキー']},
            { emoji: ':blobcatnomfish:', keywords: ['たいやき', 'たい焼き']},
            { emoji: ':blobcatnomonigiri:', keywords: ['おにぎり', 'おににに']},
            { emoji: ':blobcatnompopsicle:', keywords: ['アイス', 'サーティーワン']},
            { emoji: ':blobcatnomtomato:', keywords: ['トマト']},
            { emoji: ':blobcatnomwatermelon2:', keywords: ['すいか', 'スイカ']},
            { emoji: ':blobcatpacifier:', keywords: ['ミルク', '牛乳']},
            { emoji: ':blobcatpizza:', keywords: ['ピザ']},
            { emoji: ':blobcattomato:', keywords: ['トマト']},
            { emoji: ':brobcat_inhale_the_milkshake:', keywords: ['シェイク', 'マックシェイク', 'モスシェイク']},
            { emoji: ':meow_can:', keywords: ['鯖', 'サバ', '鯖缶']},
            { emoji: ':meow_cookie:', keywords: ['クッキー']},
            { emoji: ':meow_fishnom:', keywords: ['寿司', '魚']},
            { emoji: ':meow_pan', keywords: ['パン']},
            { emoji: ':meow_peach:', keywords: ['桃']},
            { emoji: ':meowpopcorn', keywords: ['ポップコーン']},
            { emoji: ':meowpumpkin:', keywords: ['かぼちゃ']},
            { emoji: ':meow_sip:', keywords: ['ジュース']},
            { emoji: ':meow_sipsmile:', keywords: ['ジュース']},
            { emoji: ':meow_sushi:', keywords: ['寿司', 'まぐろ']},
            { emoji: ':meow_sushihamachi:', keywords: ['寿司', 'はまち']},
            { emoji: ':meow_sushiikura:', keywords: ['寿司', 'いくら']},
            { emoji: ':meow_sushitamago:', keywords: ['寿司', 'たまご']},
            { emoji: ':meow_wine:', keywords: ['ワイン', 'デカンタ', '酒']},
            
            { emoji: ':tabetera:', keywords: ['いただきます']},

            // nekonya
            { emoji: ':neko_beer_nya:', keywords: ['ビール']},
            { emoji: ':neko_buriburiburiburi_muchaburi_nya:', keywords: ['ブリ', '鰤', '魚']},
            { emoji: ':neko_gohan_taberu_nya:', keywords: ['ごはん']},
            { emoji: ':neko_nihonshu_nya:', keywords: ['日本酒', '焼酎']},
            { emoji: ':neko_ocha_nya:', keywords: ['お茶']},
            
            // こしゃんぶろきゃ
            { emoji: ':ablobcat_drinkwater:', keywords: ['お水', '飲み物']},
            { emoji: ':ablobcat_mayochuchu:', keywords: ['ツナマヨ', 'マヨネーズ']},
            { emoji: ':ablobcat_onigiri:', keywords: ['おにぎり']},
            { emoji: ':ablobcat_opensnackpouch:', keywords: ['ポテチ', 'ポテトチップス']},
            { emoji: ':blobcat_indonuts:', keywords: ['ドーナツ', 'ミスド', 'ミスタードーナツ']},

            // こまくさぶろきゃ
            { emoji: ':blobcat_beer:', keywords: ['ビール']},
            { emoji: ':blobcat_meshiyosoi:', keywords: ['ごはん', 'メシヨソイ']},
            { emoji: ':blobcat_peperoncino_ehomaki:', keywords: ['恵方巻き', '太巻き']},
            { emoji: ':blobcat_peperoncino_sobachuruchuru:', keywords: ['蕎麦', 'ラーメン', 'パスタ', 'スパゲッティ']},

            // くまぷ
            { emoji: ':kumapu_takoyaki:', keywords: ['たこせん', 'たこやき', 'たこ焼き']},
            { emoji: ':kumapu_whisky:', keywords: ['イウシキー', 'ウイスキー', '酒', 'そうやなす']},

            // しろぷよ
            { emoji: ':Shiropuyo_apple:', keywords: ['りんご', '林檎']},
            { emoji: ':Shiropuyo_bacon:', keywords: ['ベーコン']},
            { emoji: ':shiropuyo_cookie:', keywords: ['クッキー']},
            { emoji: ':Shiropuyo_drink_tea:', keywords: ['お茶', '緑茶']},
            { emoji: ':Shiropuyo_drink_water:', keywords: ['お水']},
            { emoji: ':Shiropuyo_eat:', keywords: ['いただきます']},
            { emoji: ':Shiropuyo_gunkanmaki:', keywords: ['寿司', '軍艦巻き']},
            { emoji: ':Shiropuyo_icecream:', keywords: ['アイス', 'ソフトクリーム']},
            { emoji: ':Shiropuyo_ikinoiikakihahuraidayo:', keywords: ['牡蠣', 'カキ']},
            { emoji: ':Shiropuyo_marshmallow:', keywords: ['マシュマロ']},
            { emoji: ':Shiropuyo_marshmallow_B:', keywords: ['マシュマロ']},
            { emoji: ':Shiropuyo_mican:', keywords: ['みかん', '蜜柑']},
            { emoji: ':Shiropuyo_pudding:', keywords: ['プリン']},
            { emoji: ':Shiropuyo_shrimp:', keywords: ['エビ', '海老']},
            { emoji: ':Shiropuyo_sushi:', keywords: ['寿司', '鮪', 'マグロ']},
            { emoji: ':Shiropuyo_takoyaki:', keywords: ['たこ焼き']},

            // しろぷよファンアート
            { emoji: ':Shiropuyo_hug_ramen:', keywords: ['カップ麺', 'カプ麺', 'カップラーメン']},
            { emoji: ':shiropuyo_pudding:', keywords: ['プリン']},

            // ぴよたそ
            { emoji: ':shokupantorampolyn_piyotaso:', keywords: ['食パン']},

            // しゃー
            { emoji: ':blobhaj_hold_sausage:', keywords: ['ウインナー', 'ソーセージ']},

            // ぶろぶ
            { emoji: ':agooglecake:', keywords: ['ケーキ']},
            { emoji: ':agooglecheers:', keywords: ['ビール', '酒']},
            { emoji: ':agoogleoctopus:', keywords: ['蛸', 'たこ']},
            { emoji: ':agooglewine:', keywords: ['ワイン', 'デカンタ']},
            { emoji: ':blobclosesip:', keywords: ['ジュース']},
            { emoji: ':blob_eating_ehou_maki:', keywords: ['恵方巻き', '太巻き']},

            // こゃ
            { emoji: ':blobfoxwater:', keywords: ['お水']},

            // いきもの
            { emoji: ':blobtakosan:', keywords: ['たこ', 'ウインナー']},
            { emoji: ':bokenasu_hatena:', keywords: ['ナス', '茄子']},
            { emoji: ':nukun_ehomaki:', keywords: ['恵方巻き', '太巻き']},
            { emoji: ':hiyayakko_only:', keywords: ['冷奴', 'ひややっこ']},

            // たべもの
            { emoji: ':alfort_orega_ichibann_sukina_chocolate:', keywords: ['きのこの山', 'たけのこの里', 'アルフォート']},
            { emoji: ':atuage:', keywords: ['厚揚げ']},
            { emoji: ':bakedmochocho_real:', keywords: ['御座候']},
            { emoji: ':chikuwa:', keywords: ['ちくわ', '竹輪']},
            { emoji: ':coffee_milk:', keywords: ['コーヒー牛乳']},
            { emoji: ':colorful_macaron_no_illust:', keywords: ['マカロン']},
            { emoji: ':cream_pasta_carbonara_illust:', keywords: ['パスタ', 'スパゲッティ', 'カルボナーラ']},
            { emoji: ':dekai_hamburger:', keywords: ['ハンバーガー']},
            { emoji: ':dragon_fruit:', keywords: ['ドラゴンフルーツ']},
            { emoji: ':food_corn_soup_illust:', keywords: ['コーンスープ', 'コーンポタージュ']},
            { emoji: ':food_kebab_illust:', keywords: ['ケバブ']},
            { emoji: ':gyuunyu:', keywords :['牛乳', 'ミルク']},
            { emoji: ':kanure:', keywords: ['カヌレ']},
            { emoji: ':katsuo:', keywords: ['鰹', 'カツオ']},
            { emoji: ':madai:', keywords: ['鯛']},
            { emoji: ':mix_nuts_illust:', keywords: ['ミックスナッツ']},
            { emoji: ':naan:', keywords: ['ナン']},
            { emoji: ':nama_ham_illust:', keywords: ['生ハム']},
            { emoji: ':nuiahesi_omelette:', keywords: ['オムレツ']},
            { emoji: ':peppermint_oil:', keywords: ['ハッカ油']},
            { emoji: ':salmon_wo_summon_w:', keywords: ['サーモン']},
            { emoji: ':sanma:', keywords: ['サンマ', '秋刀魚']},
            { emoji: ':sasakama:', keywords: ['笹かま', 'ささかま']},
            { emoji: ':shirasudon:', keywords: ['しらす丼']},
            { emoji: ':slice_steak_illust:', keywords: ['カットステーキ']},
            { emoji: ':surumeika_dual:', keywords: ['スルメイカ', 'するめいか']},
            { emoji: ':taifukuroiri:', keywords: ['鯛']},
            { emoji: ':tamagokakegohan:', keywords: ['卵かけご飯', 'TKG', 'たまごかけごはん']},
            { emoji: ':tuna_canned_baskeyn_bsk:', keywords: ['ツナ缶']},
            { emoji: ':tunacan_p4dr_rear:', keywords: ['ツナ缶']},
            { emoji: ':uni_bsk:', keywords: ['雲丹', 'ウニ']},

            // たべもの（かわいい顔）
            { emoji: ':cute_akebi_character:', keywords: ['木通', '通草', 'アケビ']},
            { emoji: ':cute_apple_character:', keywords: ['林檎', 'りんご', 'リンゴ']},
            { emoji: ':cute_avocado_character:', keywords: ['アボガド', 'アボカド']},
            { emoji: ':cute_banana_character:', keywords: ['バナナ', 'ばなな']},
            { emoji: ':cute_beans_character:', keywords: ['青豆']},
            { emoji: ':cute_biwa_character:', keywords: ['ビワ', '枇杷']},
            { emoji: ':cute_blueberry_character:', keywords: ['ブルーベリー']},
            { emoji: ':cute_broccoli_character:', keywords: ['ブロッコリー']},
            { emoji: ':cute_cabbage_character:', keywords: ['キャベツ']},
            { emoji: ':cute_carrot_character:', keywords: ['人参', 'ニンジン']},
            { emoji: ':cute_cauliflower_character:', keywords: ['カリフラワー']},
            { emoji: ':cute_cherry_character:', keywords: ['さくらんぼ', 'サクランボ']},
            { emoji: ':cute_corn_character:', keywords: ['とうもろこし', 'コーン']},
            { emoji: ':cute_cucumber_character:', keywords: ['きゅうり', 'キュウリ', '胡瓜']},
            { emoji: ':cute_eggplant_character:', keywords: ['茄子', 'ナス']},
            { emoji: ':cute_fig_character:', keywords: ['いちじく', 'イチジク', '無花果']},
            { emoji: ':cute_fruit_kaki_character:', keywords: ['柿']},
            { emoji: ':cute_garlic_character:', keywords: ['ガーリック', 'にんにく']},
            { emoji: ':cute_gobou_character:', keywords: ['牛蒡', 'ごぼう', 'ゴボウ']},
            { emoji: ':cute_grape_character:', keywords: ['ぶどう', 'ブドウ', '葡萄']},
            { emoji: ':cute_green_apple_character:', keywords: ['青りんご', '青リンゴ']},
            { emoji: ':cute_greenpepper_character:', keywords: ['ピーマン']},
            { emoji: ':cute_guava_character:', keywords: ['グアバ']},
            { emoji: ':cute_hakusai_character:', keywords: ['白菜', 'はくさい']},
            { emoji: ':cute_hourensou_character:', keywords: ['ほうれん草', 'ほうれんそう']},
            { emoji: ':cute_kiwi_character:', keywords: ['キウイフルーツ']},
            { emoji: ':cute_la_france_character:', keywords: ['洋梨', 'ラ・フランス', 'ラフランス']},
            { emoji: ':cute_lemon_character:', keywords: ['レモン', '檸檬']},
            { emoji: ':cute_lettuce_character:', keywords: ['レタス']},
            { emoji: ':cute_mango_character:', keywords: ['マンゴー']},
            { emoji: ':cute_melon_character:', keywords: ['メロン']},
            { emoji: ':cute_mikan_character:', keywords: ['蜜柑', 'みかん', 'ミカン']},
            { emoji: ':cute_mini_tomato_character:', keywords: ['ミニトマト']},
            { emoji: ':cute_muscat_character:', keywords: ['マスカット']},
            { emoji: ':cute_negi_character:', keywords: ['ねぎ', '葱']},
            { emoji: ':cute_onion_character:', keywords: ['玉葱', 'たまねぎ']},
            { emoji: ':cute_peach_character:', keywords: ['桃', 'ピーチ']},
            { emoji: ':cute_pineapple_character:', keywords: ['パイナップル']},
            { emoji: ':cute_potato_character:', keywords: ['じゃがいも', 'ジャガイモ']},
            { emoji: ':cute_pumpkin_character:', keywords: ['かぼちゃ', 'カボチャ', '南瓜']},
            { emoji: ':cute_radish_character:', keywords: ['大根']},
            { emoji: ':cute_raspberry_character:', keywords: ['ラズベリー']},
            { emoji: ':cute_redpepper_character:', keywords: ['唐辛子', 'とうがらし']},
            { emoji: ':cute_renkon_character:', keywords: ['蓮根', 'れんこん']},
            { emoji: ':cute_satoimo_character:', keywords: ['里芋', 'さといも']},
            { emoji: ':cute_shiitake_character:', keywords: ['椎茸', 'しいたけ']},
            { emoji: ':cute_strawberry_character:', keywords: ['苺', 'いちご']},
            { emoji: ':cute_sudachi_character:', keywords: ['すだち', '酢橘']},
            { emoji: ':cute_suika_character:', keywords: ['すいか', 'スイカ']},
            { emoji: ':cute_sweetpotato_character:', keywords: ['さつまいも', 'サツマイモ']},
            { emoji: ':cute_tomato_character:', keywords: ['トマト']},

            // 実写ほか
            { emoji: ':551_horai_butaman:', keywords: ['551', '蓬莱']},

            // もじ
            { emoji: ':dom_dom:', keywords: ['ドムドム']},
            { emoji: ':yasai_seikatsu:', keywords: ['やさいせいかつ', '野菜']},
            
            // サーティーワン
            { emoji: ':31_party:', keywords: ['サーティーワンパーティ']},
            { emoji: ':apple_sorbet:', keywords: ['りんごソルベ']},
            { emoji: ':banana_and_strawberry:', keywords: ['バナナアンドストロベリー']},
            { emoji: ':burgundy_cherry:', keywords: ['バーガンディチェリー']},
            { emoji: ':candy_apple:', keywords: ['キャンディアップル']},
            { emoji: ':caramel_matcha_au_lait:', keywords: ['キャラメル抹茶オレ']},
            { emoji: ':caramel_ribbon:', keywords: ['キャラメルリボン']},
            { emoji: ':chocolate:', keywords: ['チョコレート']},
            { emoji: ':choped_chocolate:', keywords: ['チョップドチョコレート']},
            { emoji: ':coconut_globe:', keywords: ['ココナッツグローブ']},
            { emoji: ':cookie_and_cream:', keywords: ['クッキーアンドクリーム']},
            { emoji: ':cotton_candy:', keywords: ['コットンキャンディ']},
            { emoji: ':crunchy_peanut_and_chocolate:', keywords: ['クランチーピナッツアンドチョコレート']},
            { emoji: ':dainagon_azuki:', keywords: ['大納言あずき']},
            { emoji: ':daiquiri_ice:', keywords: ['ダイキュリーアイス']},
            { emoji: ':french_vanilla:', keywords: ['フレンチバニラ']},
            { emoji: ':green_tea:', keywords: ['抹茶']},
            { emoji: ':jamoca_almond_fudge:', keywords: ['ジャモカアーモンドファッジ']},
            { emoji: ':jamoca_coffee:', keywords: ['ジャモカコーヒー']},
            { emoji: ':lemon_sorbet:', keywords: ['レモンシャーベット']},
            { emoji: ':love_potion_31:', keywords: ['ラブポ']},
            { emoji: ':magical_mint_night:', keywords: ['マジカルミッドナイト']},
            { emoji: ':musk_melon:', keywords: ['マスクメロン']},
            { emoji: ':nuts_to_you:', keywords: ['ナッツトゥーユー']},
            { emoji: ':opera_the_symphony:', keywords: ['オペラザシンフォニー']},
            { emoji: ':orange_sorbet:', keywords: ['オレンジソルベ']},
            { emoji: ':popping_shower:', keywords: ['ポッピングシャワー']},
            { emoji: ':rocky_road:', keywords: ['ロッキーロード']},
            { emoji: ':rum_raisin:', keywords: ['ラムレーズン']},
            { emoji: ':soda_float:', keywords: ['ソーダフロート']},
            { emoji: ':strawberry_cheesecake:', keywords: ['ストロベリーチーズケーキ']},
            { emoji: ':sunset_surfing:', keywords: ['サンセットサーフィン']},
            { emoji: ':vampires_treat:', keywords: ['ヴァンパイアのおやつ']},
            { emoji: ':vanilla:', keywords: ['バニラ']},
            { emoji: ':very_berry_strawberry:', keywords: ['ベリーベリーストロベリー']},

            // たべもの
            { emoji: ':avocado:', keywords: ['アボカド']},
            { emoji: ':beckon_become_bacon:', keywords: ['ベーコン']},
            { emoji: ':beni_imo_tart:', keywords: ['紅芋タルト']},
            { emoji: ':cocoa_kotoba:', keywords: ['ココア']},
            { emoji: ':color_ge:', keywords: ['からあげ', 'から揚げ', '唐揚げ']},
            { emoji: ':corn_soup:', keywords: ['コーンスープ']},
            { emoji: ':fish_yaki:', keywords: ['焼き魚']},
            { emoji: ':gi_yoza:', keywords: ['餃子']},
            { emoji: ':hambger:', keywords: ['ハンバーガー']},
            { emoji: ':Hambgur:', keywords: ['ハンバーグ']},
            { emoji: ':jaga_butter:', keywords: ['じゃがバター']},
            { emoji: ':jagaimo:', keywords: ['じゃがいも']},
            { emoji: ':ketsune_udon:', keywords: ['きつねうどん']},
            { emoji: ':koshian_no_hou_ga_oishii:', keywords: ['おはぎ']},
            { emoji: ':milk:', keywords: ['ミルク', '牛乳']},
            { emoji: ':mori_mitaina_yatsu:', keywords: ['ブロッコリー']},
            { emoji: ':mori_mitaina_yatsu_no_shiroi_hou:', keywords: ['カリフラワー', 'フラワーカリ']},
            { emoji: ':nabeparty:', keywords: ['鍋']},
            { emoji: ':nattou:', keywords: ['納豆']},
            { emoji: ':okaki:', keywords: ['おかき']},
            { emoji: ':onigiri_konbu:', keywords: ['昆布', 'こんぶ']},
            { emoji: ':onigiri_mentaiko:', keywords: ['明太子']},
            { emoji: ':onigiri_okaka:', keywords: ['おかか']},
            { emoji: ':onigiri_tarako:', keywords: ['たらこ']},
            { emoji: ':onigiri_tsunamayo:', keywords: ['ツナマヨ']},
            { emoji: ':onigiri_ume:', keywords: ['梅おにぎり', '梅のおにぎり']},
            { emoji: ':oninini:', keywords: ['おにぎり', 'おににに']},
            { emoji: ':potato:', keywords: ['ポテト']},
            { emoji: ':ra_don:', keywords: ['うどん', 'ラーメン']},
            { emoji: ':ra_men:', keywords: ['ラーメン']},
            { emoji: ':salmon:', keywords: ['サーモン']},
            { emoji: ':shumai:', keywords: ['しゅうまい']},
            { emoji: ':steak:', keywords: ['ステーキ']},
            { emoji: ':sunny_lettuce:', keywords: ['サニーレタス']},
            { emoji: ':tiya_hen:', keywords: ['チャーハン', '焼飯', '焼き飯']},
            { emoji: ':tokoroten:', keywords: ['ところてん']},
            { emoji: ':udon:', keywords: ['うどん', '饂飩']},
            { emoji: ':u_men:', keywords: ['ラーメン', 'うどん']},
            { emoji: ':yakiimo:', keywords: ['焼き芋']},

            // 御座候
            { emoji: ':gozasourou:', keywords: ['御座候']},




            // ちくちくしてない言葉

        ],
    },
};
